services:
  springboot-app:
    image: api-reserva-vuelos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
     - api-reserva-vuelos
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-quiet-feather-a4y06yn1.us-east-1.aws.neon.tech/neondb
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_tzL3yU8HnjED
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - api-reserva-vuelos


networks:
  api-reserva-vuelos:
    driver: bridge